### ISSUE TITLE
Numcodecs 0.7.0 fails with Zarr package

### ISSUE THREAD

**Issue by yihming** [zarr-developers/numcodecs#243]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
from zarr import Blosc

```

#### Problem description

I installed `numcodecs` latest 0.7.0 version, but found that `zarr` did not work properly with it. Downgrading `numcodecs` to version 0.6.4 resolved this issue.

Moreover, I had to install a bunch of dependency head files in Ubuntu to make the installation of `numcodecs` v0.7.0 succeed (see below):
```
sudo apt install libblosc-dev libzstd-dev liblz4-dev
conda activate pegasus-python37
pip install zarr
```
Then the code sample above gives the following error message:

```
>>> from zarr import Blosc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Blosc' from 'zarr' (/opt/miniconda3/envs/pegasus-python37/lib/python3.7/site-packages/zarr/__init__.py)
```

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__``: 0.7.0
* Version of Python interpreter: 3.7.9
* Operating system (Linux/Windows/Mac): Ubuntu Linux 20.04
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda"): In conda environment, use `pip install numcodecs`.

My `zarr` version is 2.4.0.

Also, if you think it might be relevant, please provide the output from ``pip list`` or
``conda list`` depending on which was used to install NumCodecs.

**Comment by ronpandolfi** [comment]
Probably related to my issue. Seems like the 0.7.0 distros are missing some components (like blosc):
https://github.com/zarr-developers/numcodecs/issues/242

**Comment by jakirkham** [comment]
Duplicate of https://github.com/zarr-developers/numcodecs/issues/242

**Comment by jakirkham** [comment]
Closing to consolidate conversation. Please follow along in issue ( https://github.com/zarr-developers/numcodecs/issues/242 ). Thanks!

**Comment by joshmoore** [comment]
@yihming, I just pushed out 0.7.1 which appears to work in a fresh ubuntu:16.04 docker image:

```
    1  apt-get install libblosc-dev libzstd-dev liblz4-dev # Likely 
    2  apt-get update
    4  apt-get install python3
    9  apt-get install python3-venv
   10  python3 -m venv /tmp/z
   12  /tmp/z/bin/pip install -U pip
   14  /tmp/z/bin/pip install -U setuptools
   15  /tmp/z/bin/pip install zarr
   16  /tmp/z/bin/python -c "from zarr import Blosc"
```

**Comment by yihming** [comment]
Thank you so much for your quick response. I'll try it later and let you know.

**Comment by yihming** [comment]
Version 0.7.1 works properly with zarr now. Thank you again for your work!
